language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  api_key:
    secure: lhXqlsRQpcvTh2+GFaX4xml73nIn8IiUsHgPu4PUJxpEqklWUa64R9wj2k/a1hSdHBBSJF93Q5c93sJJUMJCipvHM2VKVrz2WsOixETISFReMzb+V/LyZwIloOMbqpm9o/GxWlJ2hiCs1GLjFSgLkCHyov9pVUeBHjv80CMK1XO39OhAFRwxif3+xQKswInOns6JE7Iz0W2i3N+GlHHQM+syp54tUYUOhq5PpaYwdjMJ6FkklrNgYGf8VAU4gwx/hsx8kKCsw16Youv1xs4jPvKmkz8lX4JQxNKQy48jrLooIkbRr1SGN5D40pVcoYfqzjUwHvgaGFRgiA28nMSU0AQ+Em0EF1u10hO2+SJzpX+IqtNrgi0DFd12Ls7vUpHpV2FhAV8un6BnmQg3x6pK7qZp8cDfUFF10Q0XloerkcaKWohvy2A9px2w296GNNWd6LTolOC2COMBQl3y9A/5yyJeplQ82AyuUIxJNLEKmxbF0+hlKXKS4q1AKti0MLuzIHYrGc2598801bjWNnFiwVdLo9km5EA2B76hu8YppD9i20qCF5qh/2uShsAQ286tLxisgb00yfreXYghrx2f5MeRcqWIZcOOs5RvmOIj4gcNCFno/bPLc3OAbO/DoePFMdZht7oV8r/SBsqjzh9g0CxBcGvOIKmVrvqRAj9xb9Q=
  app: sesion6-travis-heroku-ricardo
  on:
    repo: organizacion-sesion-3-ricardo-sanchez/sesion6-travis-heroku-ricardo
  skip_cleanup: 'true'
